# Site settings
title: Nicolas Guetta-Jeanrenaud
email: nicolas.jeanrenaud@gmail.com
description: Nicolas Guetta-Jeanrenaud's personal website.
# It will appear in your document head meta (for Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nicogj.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: nicogj_
github_username:  nicogj
linkedin_username: nicolas-guetta-jeanrenaud-4348b486
email_username: nicolas.jeanrenaud@gmail.com
google_analytics: UA-131722816-1

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
